#!/usr/bin/env python
import optparse
import sys
from collections import defaultdict
import itertools

optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--threshold", dest="threshold", default=0.5, type="float", help="Threshold for aligning with Dice's coefficient (default=0.5)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

sys.stderr.write("\n")
bitext = [[sentence.strip().split() for sentence in pair] for pair in zip(open(f_data), open(e_data))[:opts.num_sents]]

iters = 0
p2 = defaultdict(float)
count2 = defaultdict(int)
e_count2 = defaultdict(int)

p = defaultdict(float)
count = defaultdict(int)
e_count = defaultdict(int)
while iters < 100:
	sys.stderr.write(str(iters))
	count = defaultdict(int)
	e_count = defaultdict(int)
	
	count2 = defaultdict(int)
	e_count2 = defaultdict(int)
	
	for (n, (f, e)) in enumerate(bitext):
		for (i, f_i) in enumerate(set(f)):
			#sys.stderr.write(str(len(e)) + " ")
			z = 0
			for (j, e_j) in enumerate(set(e)):
				if p[(f_i, e_j)] == 0.0:
					p[(f_i, e_j)] = 0.001
				z += p[(f_i, e_j)]
				
			for (j, e_j) in enumerate(set(e)):
				if (abs(i - j) < 5 or True):
					c = p[(f_i, e_j)] / z
					count[(f_i, e_j)] += c
					e_count[e_j] += c
				
		for (i, e_i) in enumerate(set(e)):
			z = 0
			for (j, f_j) in enumerate(set(f)):
				if p2[(e_i, f_j)] == 0.0:
					p2[(e_i, f_j)] = 0.001
				z += p2[(e_i, f_j)]
				
			for (j, f_j) in enumerate(set(f)):
				if (abs(i - j) < 5 or True):
					c = p2[(e_i, f_j)] / z
					count2[(e_i, f_j)] += c
					e_count2[f_j] += c
		if n % 1000 == 0:
			sys.stderr.write(".")

	for (k, (f_i, e_j)) in enumerate(count.keys()):
		p[(f_i,e_j)] = float(count[(f_i, e_j)]) / e_count[e_j] 
		if k % 120000 == 0:
			sys.stderr.write("-")
	for (k, (e_i, f_j)) in enumerate(count2.keys()):
		p2[(e_i, f_j)] = float(count2[(e_i, f_j)]) / e_count2[f_j]
		if k % 120000 == 0:
			sys.stderr.write("-")
	sys.stderr.write("\n")
	iters += 1


for (n, (f, e)) in enumerate(bitext):
		for (i, f_i) in enumerate(f):
			bestp = 0
			bestj = 0
			for (j, e_j) in enumerate(e):
				if p[(f_i, e_j)] * p2[(e_j, f_i)] * (1/(abs(i-j) / 8 + 1)) > bestp:
					bestp = p[(f_i, e_j)] * p2[(e_j, f_i)]
					bestj = j
			sys.stdout.write("%i-%i " % (i,bestj))
		sys.stdout.write("\n")